import type { UserRole } from "@/types/roles";

export const ROUTE_ACCESS_FIXTURE: Record<Exclude<UserRole, "public">, { allowed: string[]; denied: string[] }> = {
  admin: {
    allowed: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/admin/msmes",
      "/dashboard/admin/verifications",
      "/dashboard/admin/digital-ids",
      "/dashboard/admin/associations",
      "/dashboard/admin/association-members",
      "/dashboard/admin/association-upload",
      "/dashboard/admin/complaints",
      "/dashboard/impact-intelligence",
      "/dashboard/impact-intelligence/programmes",
      "/dashboard/impact-intelligence/cohorts",
      "/dashboard/impact-intelligence/interventions",
      "/dashboard/impact-intelligence/assessments",
      "/dashboard/impact-intelligence/monitoring",
      "/dashboard/impact-intelligence/evidence",
      "/dashboard/impact-intelligence/indicators",
      "/dashboard/impact-intelligence/executive",
      "/dashboard/impact-intelligence/analytics",
      "/dashboard/impact-intelligence/reports",
      "/dashboard/lcdbo",
      "/dashboard/lcdbo/delivery",
      "/dashboard/lcdbo/workstreams",
      "/dashboard/lcdbo/milestones",
      "/dashboard/lcdbo/raid",
      "/dashboard/lcdbo/decisions",
      "/dashboard/lcdbo/calendar",
      "/dashboard/lcdbo/intelligence",
      "/dashboard/lcdbo/reports",
      "/dashboard/admin/public-verification",
    ],
    denied: [],
  },
  super_admin: {
    allowed: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/admin/msmes",
      "/dashboard/admin/verifications",
      "/dashboard/admin/digital-ids",
      "/dashboard/admin/associations",
      "/dashboard/admin/association-members",
      "/dashboard/admin/association-upload",
      "/dashboard/admin/complaints",
      "/dashboard/impact-intelligence",
      "/dashboard/impact-intelligence/programmes",
      "/dashboard/impact-intelligence/cohorts",
      "/dashboard/impact-intelligence/interventions",
      "/dashboard/impact-intelligence/assessments",
      "/dashboard/impact-intelligence/monitoring",
      "/dashboard/impact-intelligence/evidence",
      "/dashboard/impact-intelligence/indicators",
      "/dashboard/impact-intelligence/executive",
      "/dashboard/impact-intelligence/analytics",
      "/dashboard/impact-intelligence/reports",
      "/dashboard/lcdbo",
      "/dashboard/lcdbo/delivery",
      "/dashboard/lcdbo/workstreams",
      "/dashboard/lcdbo/milestones",
      "/dashboard/lcdbo/raid",
      "/dashboard/lcdbo/decisions",
      "/dashboard/lcdbo/calendar",
      "/dashboard/lcdbo/intelligence",
      "/dashboard/lcdbo/reports",
      "/dashboard/admin/public-verification",
    ],
    denied: [],
  },
  reviewer: {
    allowed: ["/dashboard/reviews", "/dashboard/compliance"],
    denied: ["/dashboard/nrs", "/dashboard/associations"],
  },
  boi_executive: {
    allowed: ["/dashboard/boi", "/dashboard/boi/businesses", "/dashboard/boi/businesses/example", "/dashboard/boi/funding-programmes", "/dashboard/boi/funding-pipeline", "/dashboard/boi/readiness", "/dashboard/boi/readiness/templates", "/dashboard/boi/documents", "/dashboard/boi/portfolio", "/dashboard/boi/monitoring", "/dashboard/boi/intelligence", "/dashboard/boi/reports", "/dashboard/boi/risk", "/dashboard/boi/executive", "/dashboard/boi/business-pipeline", "/dashboard/boi/investment-readiness", "/dashboard/impact-intelligence", "/dashboard/impact-intelligence/programmes", "/dashboard/impact-intelligence/cohorts", "/dashboard/impact-intelligence/interventions", "/dashboard/impact-intelligence/assessments", "/dashboard/impact-intelligence/monitoring", "/dashboard/impact-intelligence/evidence", "/dashboard/impact-intelligence/indicators", "/dashboard/impact-intelligence/executive", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/reports"],
    denied: ["/dashboard/lcdbo", "/dashboard/msme", "/dashboard/admin"],
  },
  programme_officer: {
    allowed: ["/dashboard/impact-intelligence", "/dashboard/impact-intelligence/programmes", "/dashboard/impact-intelligence/cohorts", "/dashboard/impact-intelligence/interventions", "/dashboard/impact-intelligence/assessments", "/dashboard/impact-intelligence/monitoring", "/dashboard/impact-intelligence/evidence", "/dashboard/impact-intelligence/indicators", "/dashboard/impact-intelligence/reports", "/dashboard/lcdbo", "/dashboard/lcdbo/delivery", "/dashboard/lcdbo/workstreams", "/dashboard/lcdbo/milestones", "/dashboard/lcdbo/raid", "/dashboard/lcdbo/decisions", "/dashboard/lcdbo/calendar", "/dashboard/lcdbo/reports"],
    denied: ["/dashboard/impact-intelligence/assessments/templates", "/dashboard/impact-intelligence/executive", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/intelligence", "/dashboard/impact-intelligence/risk-flags", "/dashboard/msme", "/dashboard/admin"],
  },
  assessment_officer: {
    allowed: ["/dashboard/impact-intelligence", "/dashboard/impact-intelligence/programmes", "/dashboard/impact-intelligence/cohorts", "/dashboard/impact-intelligence/interventions", "/dashboard/impact-intelligence/assessments", "/dashboard/impact-intelligence/monitoring", "/dashboard/impact-intelligence/evidence", "/dashboard/impact-intelligence/indicators", "/dashboard/impact-intelligence/executive", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/reports", "/dashboard/impact-intelligence/intelligence", "/dashboard/impact-intelligence/risk-flags"],
    denied: ["/dashboard/msme", "/dashboard/admin"],
  },
  field_officer: {
    allowed: ["/dashboard/impact-intelligence", "/dashboard/impact-intelligence/cohorts", "/dashboard/impact-intelligence/monitoring", "/dashboard/impact-intelligence/evidence", "/dashboard/impact-intelligence/indicators"],
    denied: ["/dashboard/msme", "/dashboard/admin", "/dashboard/impact-intelligence/programmes", "/dashboard/impact-intelligence/interventions", "/dashboard/impact-intelligence/assessments", "/dashboard/impact-intelligence/executive", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/reports", "/dashboard/impact-intelligence/intelligence", "/dashboard/impact-intelligence/risk-flags"],
  },
  data_analyst: {
    allowed: ["/dashboard/impact-intelligence", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/indicators", "/dashboard/impact-intelligence/reports", "/dashboard/impact-intelligence/intelligence", "/dashboard/impact-intelligence/risk-flags", "/dashboard/lcdbo/delivery", "/dashboard/lcdbo/workstreams", "/dashboard/lcdbo/milestones", "/dashboard/lcdbo/raid", "/dashboard/lcdbo/decisions", "/dashboard/lcdbo/calendar", "/dashboard/lcdbo/intelligence", "/dashboard/lcdbo/reports"],
    denied: ["/dashboard/msme", "/dashboard/admin"],
  },
  auditor: {
    allowed: ["/dashboard/impact-intelligence", "/dashboard/impact-intelligence/programmes", "/dashboard/impact-intelligence/cohorts", "/dashboard/impact-intelligence/interventions", "/dashboard/impact-intelligence/assessments", "/dashboard/impact-intelligence/monitoring", "/dashboard/impact-intelligence/evidence", "/dashboard/impact-intelligence/indicators", "/dashboard/impact-intelligence/executive", "/dashboard/impact-intelligence/analytics", "/dashboard/impact-intelligence/reports", "/dashboard/lcdbo/delivery", "/dashboard/lcdbo/workstreams", "/dashboard/lcdbo/milestones", "/dashboard/lcdbo/raid", "/dashboard/lcdbo/decisions", "/dashboard/lcdbo/calendar", "/dashboard/lcdbo/intelligence", "/dashboard/lcdbo/reports"],
    denied: ["/dashboard/msme", "/dashboard/admin"],
  },
  msme: {
    allowed: ["/dashboard/msme", "/dashboard/msme/onboarding", "/dashboard/msme/id-card", "/dashboard/msme/payments"],
    denied: ["/dashboard/reviews", "/dashboard/nrs", "/dashboard"],
  },
  association_officer: {
    allowed: ["/dashboard/associations", "/dashboard/reports"],
    denied: ["/dashboard/reviews", "/dashboard/nrs"],
  },
  fccpc_officer: {
    allowed: ["/dashboard/fccpc"],
    denied: ["/dashboard/reviews", "/dashboard/payments"],
  },
  nrs_officer: {
    allowed: ["/dashboard/nrs", "/dashboard/nrs/businesses", "/dashboard/nrs/businesses/example", "/dashboard/nrs/readiness", "/dashboard/nrs/intelligence", "/dashboard/nrs/revenue-guides", "/dashboard/nrs/programmes", "/dashboard/nrs/reports", "/dashboard/nrs/verification", "/dashboard/nrs/integrations", "/dashboard/nrs/invoices", "/dashboard/nrs/invoice-registry", "/dashboard/nrs/vat-monitor", "/dashboard/nrs/revenue", "/dashboard/firs"],
    denied: ["/dashboard/associations", "/dashboard/msme", "/dashboard/payments", "/dashboard/reviews/compliance", "/dashboard/reports"],
  },
  firs_officer: {
    allowed: ["/dashboard/nrs", "/dashboard/nrs/businesses", "/dashboard/nrs/businesses/example", "/dashboard/nrs/readiness", "/dashboard/nrs/intelligence", "/dashboard/nrs/revenue-guides", "/dashboard/nrs/programmes", "/dashboard/nrs/reports", "/dashboard/nrs/verification", "/dashboard/nrs/integrations", "/dashboard/nrs/invoices", "/dashboard/nrs/invoice-registry", "/dashboard/nrs/vat-monitor", "/dashboard/nrs/revenue", "/dashboard/firs"],
    denied: ["/dashboard/associations", "/dashboard/msme", "/dashboard/payments", "/dashboard/reviews/compliance", "/dashboard/reports"],
  },
};
