"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Pathway = "loan" | "grant" | "investment";
type Band = "High Readiness" | "Moderate Readiness" | "Low Readiness";
type Question = { id: string; prompt: string; hint: string };
type Section = { id: string; title: string; weight: number; questions: Question[] };
const STORAGE_KEY = "dbin_afri_diagnostic_v1";
const sections: Section[] = [{ id:"identity",title:"Identity & Compliance",weight:0.2,questions:[{id:"nin_bvn",prompt:"NIN and BVN are available for principal owner(s)",hint:"Supports KYC confidence."},{id:"cac",prompt:"Business has CAC registration evidence",hint:"Formalization improves finance access."},{id:"tin",prompt:"TIN is active and tax records are current",hint:"Important for loans and grants."}]},{ id:"records",title:"Financial Records",weight:0.2,questions:[{id:"bookkeeping",prompt:"Monthly bookkeeping is maintained",hint:"Lenders assess historical discipline."},{id:"bank_stmt",prompt:"12 months bank statements are available",hint:"Required by many institutions."},{id:"cashflow",prompt:"Cashflow forecast exists for next 6 months",hint:"Shows planning maturity."}]},{id:"operations",title:"Business Operations",weight:0.15,questions:[{id:"contracts",prompt:"Business has recurring contracts/purchase orders",hint:"Signals revenue visibility."},{id:"inventory",prompt:"Inventory/supply process is documented",hint:"Useful for manufacturing and trade."},{id:"insurance",prompt:"Business has basic risk cover/insurance",hint:"Reduces risk profile."}]},{id:"market",title:"Market & Traction",weight:0.15,questions:[{id:"customers",prompt:"Repeat customers represent at least 30% of sales",hint:"Indicates reliable demand."},{id:"digital",prompt:"Business has active digital presence and reviews",hint:"Improves confidence for investors."},{id:"growth",prompt:"Revenue growth in the last two quarters",hint:"Shows momentum."}]},{id:"governance",title:"Governance & Team",weight:0.15,questions:[{id:"roles",prompt:"Team roles are clearly defined",hint:"Supports scale readiness."},{id:"controls",prompt:"Expense approvals and internal controls exist",hint:"Important in diligence checks."},{id:"advisory",prompt:"Business uses accountant/advisor support",hint:"Increases reporting quality."}]},{id:"funding",title:"Funding Strategy",weight:0.15,questions:[{id:"purpose",prompt:"Use of funds is clearly defined",hint:"Lenders/investors require this."},{id:"repay",prompt:"Repayment or return plan is realistic",hint:"Critical for credit/investment."},{id:"matching",prompt:"Business has matched suitable finance providers",hint:"Improves conversion speed."}]}];
const pathwayWeights: Record<Pathway, Record<string, number>> = {loan:{identity:1.2,records:1.4,operations:1.1,market:0.9,governance:1,funding:1.4},grant:{identity:1.1,records:1.1,operations:1.1,market:1.2,governance:1.2,funding:1.3},investment:{identity:1,records:1.1,operations:1.1,market:1.4,governance:1.3,funding:1.1}};
export default function FinanceReadinessPage(){const [pathway,setPathway]=useState<Pathway>("loan");const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Record<string,boolean>>({});const [done,setDone]=useState(false);
useEffect(()=>{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;try{const p=JSON.parse(raw);setPathway(p.pathway??"loan");setStep(p.step??0);setAnswers(p.answers??{});setDone(p.done??false);}catch{}},[]);
useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify({pathway,step,answers,done}));},[pathway,step,answers,done]);
const totalQuestions=sections.reduce((a,s)=>a+s.questions.length,0);const answeredCount=Object.keys(answers).length;
const result=useMemo(()=>{const breakdown=sections.map((section)=>{const yes=section.questions.filter((q)=>answers[q.id]).length;const raw=yes/section.questions.length;const weighted=raw*section.weight*(pathwayWeights[pathway][section.id]??1);return{...section,yes,pct:Math.round(raw*100),weighted};});const max=sections.reduce((sum,s)=>sum+s.weight*(pathwayWeights[pathway][s.id]??1),0);const score=Math.round((breakdown.reduce((sum,b)=>sum+b.weighted,0)/max)*100);const band:Band=score>=75?"High Readiness":score>=50?"Moderate Readiness":"Low Readiness";return{breakdown,score,band};},[answers,pathway]);
const current=sections[step];const sectionComplete=current?.questions.every((q)=>q.id in answers);
if(done){const gaps=result.breakdown.filter((b)=>b.pct<60).map((b)=>b.title);const strengths=result.breakdown.filter((b)=>b.pct>=75).map((b)=>b.title);return <section className="space-y-5"><h1 className="text-2xl font-semibold">Access to Finance Readiness</h1><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-600">Pathway: <span className="font-semibold capitalize">{pathway}</span></p><p className="mt-2 text-4xl font-bold text-emerald-700">AFRI {result.score}</p><p className="mt-1 text-lg font-medium">{result.band}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{result.breakdown.map((b)=><div key={b.id} className="rounded-xl border p-3"><p className="font-medium">{b.title}</p><p className="text-sm text-slate-600">{b.yes}/{b.questions.length} ({b.pct}%)</p></div>)}</div><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><p className="font-semibold">Strengths</p><ul className="list-disc pl-4">{strengths.map((s)=><li key={s}>{s}</li>)}</ul></div><div><p className="font-semibold">Gaps</p><ul className="list-disc pl-4">{gaps.map((g)=><li key={g}>{g}</li>)}</ul></div><div><p className="font-semibold">Next Actions</p><ul className="list-disc pl-4"><li>Update records and re-run in 30 days.</li><li>Prepare evidence pack for selected pathway.</li></ul></div></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>window.print()} className="rounded-lg bg-emerald-700 px-4 py-2 text-white">Download PDF</button><button onClick={()=>{setDone(false);setStep(0);}} className="rounded-lg border px-4 py-2">Review Responses</button><button onClick={()=>{setPathway("loan");setStep(0);setAnswers({});setDone(false);localStorage.removeItem(STORAGE_KEY);}} className="rounded-lg border px-4 py-2">Start Fresh</button><Link href="/dashboard/msme" className="rounded-lg border px-4 py-2">Back to Dashboard</Link></div></div></section>}
return <section className="space-y-5"><header className="rounded-2xl border bg-white p-5"><h1 className="text-2xl font-semibold">Access to Finance Readiness</h1><p className="mt-1 text-sm text-slate-600">Complete the six-section AFRI diagnostic to assess Loan, Grant, or Investment readiness.</p></header><div className="rounded-2xl border bg-white p-5"><p className="text-sm font-medium">Select pathway</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{(["loan","grant","investment"] as Pathway[]).map((p)=><button key={p} onClick={()=>setPathway(p)} className={`rounded-lg border px-3 py-2 text-sm capitalize ${pathway===p?"border-emerald-600 bg-emerald-50":""}`}>{p}</button>)}</div><p className="mt-3 text-xs text-slate-500">Progress: {answeredCount}/{totalQuestions}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Section {step+1} of {sections.length}</p><h2 className="text-lg font-semibold">{current.title}</h2><div className="mt-4 space-y-3">{current.questions.map((q)=><div key={q.id} className="rounded-xl border p-4"><p className="font-medium">{q.prompt}</p><p className="text-xs text-slate-500">{q.hint}</p><div className="mt-3 flex gap-2"><button onClick={()=>setAnswers((v)=>({...v,[q.id]:true}))} className={`rounded-md border px-3 py-1.5 text-sm ${answers[q.id]===true?"bg-emerald-600 text-white":""}`}>Yes</button><button onClick={()=>setAnswers((v)=>({...v,[q.id]:false}))} className={`rounded-md border px-3 py-1.5 text-sm ${answers[q.id]===false?"bg-rose-600 text-white":""}`}>No</button></div></div>)}</div><div className="mt-5 flex gap-2"><button onClick={()=>setStep((s)=>Math.max(0,s-1))} disabled={step===0} className="rounded-lg border px-4 py-2 disabled:opacity-40">Back</button>{step<sections.length-1?<button onClick={()=>setStep((s)=>Math.min(sections.length-1,s+1))} disabled={!sectionComplete} className="rounded-lg bg-emerald-700 px-4 py-2 text-white disabled:opacity-40">Next Section</button>:<button onClick={()=>setDone(true)} disabled={!sectionComplete} className="rounded-lg bg-emerald-700 px-4 py-2 text-white disabled:opacity-40">View Results</button>}</div></div></section>}
