import { redirect } from "next/navigation";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getCurrentUserContext } from "@/lib/auth/session";
import { generateRiskFlags, listIntelligenceFeed, resolveRiskFlag } from "@/lib/data/impact-intelligence";

const INTELLIGENCE_ROLES = ["admin", "boi_executive", "programme_officer", "assessment_officer", "auditor", "field_officer"];
const MANAGE_ROLES = ["admin", "boi_executive", "programme_officer", "assessment_officer"];

async function generateRiskFlagsAction() {
  "use server";
  const ctx = await getCurrentUserContext();
  await generateRiskFlags(ctx);
  redirect("/dashboard/impact-intelligence/risk-flags");
}

async function resolveRiskFlagAction(riskFlagId: string, formData: FormData) {
  "use server";
  const ctx = await getCurrentUserContext();
  await resolveRiskFlag(ctx, riskFlagId, formData);
  redirect("/dashboard/impact-intelligence/risk-flags");
}

function severityClass(severity: string) {
  if (severity === "critical" || severity === "high") return "bg-red-100 text-red-700";
  if (severity === "medium") return "bg-amber-100 text-amber-700";
  return "bg-slate-100 text-slate-700";
}

export default async function RiskFlagsPage() {
  const ctx = await getCurrentUserContext();
  if (!INTELLIGENCE_ROLES.includes(ctx.role)) redirect("/access-denied");
  const feed = await listIntelligenceFeed(ctx, { limit: 100 });
  const canManage = MANAGE_ROLES.includes(ctx.role);
  const openFlags = feed.riskFlags.filter((flag) => flag.status === "open");

  return (
    <section className="space-y-6">
      <header className="rounded-xl border bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Risk intelligence</p>
            <h1 className="mt-2 text-2xl font-semibold text-slate-950">Risk Flags</h1>
            <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Evidence-backed operational, readiness, verification, and intervention risk indicators generated by deterministic rules.</p>
          </div>
          {canManage && (
            <form action={generateRiskFlagsAction}>
              <Button type="submit" className="gap-2"><AlertTriangle className="h-4 w-4" /> Generate risk flags</Button>
            </form>
          )}
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="rounded-lg border bg-white p-4"><p className="text-xs text-slate-500">Open risks</p><p className="mt-1 text-2xl font-semibold text-slate-950">{openFlags.length}</p></div>
        <div className="rounded-lg border bg-white p-4"><p className="text-xs text-slate-500">High priority</p><p className="mt-1 text-2xl font-semibold text-slate-950">{openFlags.filter((flag) => ["high", "critical"].includes(flag.severity)).length}</p></div>
        <div className="rounded-lg border bg-white p-4"><p className="text-xs text-slate-500">Resolved</p><p className="mt-1 text-2xl font-semibold text-slate-950">{feed.riskFlags.filter((flag) => flag.status === "resolved").length}</p></div>
      </div>

      <article className="rounded-xl border bg-white p-5 shadow-sm">
        {feed.riskFlags.length === 0 ? (
          <div className="rounded-lg border border-dashed bg-slate-50 p-6 text-center">
            <h2 className="font-semibold text-slate-950">No risk flags yet</h2>
            <p className="mt-2 text-sm text-slate-600">Run deterministic risk generation after interventions, assessments, monitoring, and evidence records exist.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {feed.riskFlags.map((flag) => {
              const resolve = resolveRiskFlagAction.bind(null, flag.id);
              return (
                <div key={flag.id} className="rounded-lg border p-4">
                  <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                    <div>
                      <p className="font-semibold text-slate-950">{flag.title}</p>
                      <p className="mt-1 text-sm text-slate-600">{flag.description}</p>
                      <p className="mt-2 text-xs text-slate-500">{flag.risk_type} • {flag.msmes?.business_name ?? flag.impact_programmes?.name ?? "portfolio"}</p>
                    </div>
                    <div className="flex shrink-0 items-center gap-2">
                      <span className={`rounded-full px-2 py-1 text-xs font-medium ${severityClass(flag.severity)}`}>{flag.severity}</span>
                      <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700">{flag.status}</span>
                    </div>
                  </div>
                  {canManage && flag.status === "open" && (
                    <form action={resolve} className="mt-4 flex flex-col gap-2 sm:flex-row">
                      <input name="resolution_note" className="min-w-0 flex-1 rounded-md border px-3 py-2 text-sm" placeholder="Resolution note" />
                      <Button type="submit" variant="secondary" className="gap-2"><ShieldCheck className="h-4 w-4" /> Resolve</Button>
                    </form>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </article>
    </section>
  );
}
