import { AlertTriangle, CheckCircle2, Database, ShieldCheck } from "lucide-react";
import { requireLcdboIntelligenceAccess } from "@/lib/auth/lcdbo-intelligence-access";
import { calculateDataQuality, calculateProgrammeHealth, getKpiDefinitions, getReportSnapshots } from "@/lib/data/lcdbo-governance";
import { getLcdboIntelligenceSnapshot } from "@/lib/data/lcdbo-intelligence";
import { createServiceRoleSupabaseClient } from "@/lib/supabase/server";
import { IntelligenceHeader, IntelligenceBarChart } from "@/components/lcdbo/lcdbo-intelligence-dashboard";
import { LcdboCommandMetricCard } from "@/components/lcdbo/lcdbo-visuals";
import { generateGovernanceSnapshotAction } from "@/app/dashboard/lcdbo/governance-actions";

export default async function LcdboDataQualityPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const { programme, ctx } = await requireLcdboIntelligenceAccess();
  const query = await searchParams;
  const supabase = await createServiceRoleSupabaseClient();
  const snapshot = await getLcdboIntelligenceSnapshot(supabase);
  const quality = calculateDataQuality(snapshot);
  const health = calculateProgrammeHealth(snapshot);
  const [trends, definitions] = await Promise.all([getReportSnapshots(programme.id, "data_quality", 12, supabase), getKpiDefinitions(programme.id, supabase)]);
  const trendData = trends.slice().reverse().map((item) => [item.snapshot_date, Number(item.metrics_payload.score ?? 0)] as [string, number]);
  const governanceReady = definitions.length > 0;
  const canGenerate = governanceReady && ["admin", "super_admin", "programme_officer"].includes(ctx.role);
  return <main className="min-h-screen bg-[#F6F8FB]"><IntelligenceHeader eyebrow="Programme Data Governance" title="LCDBO Data Quality Centre" description="Monitor completeness, integrity, geographic coverage and operational trust across the national programme dataset." actions={canGenerate ? <form action={generateGovernanceSnapshotAction} className="flex gap-2"><select name="frequency" defaultValue="monthly" className="rounded-xl border border-white/20 bg-[#082441] px-3 py-2 text-sm text-white"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select><button className="rounded-xl bg-[#D4A017] px-4 py-2 text-sm font-black text-[#0B2E59]">Capture snapshot</button></form> : null} /><div className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6">{query.success && <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Governed KPI, quality, health and national report snapshots were generated.</p>}
    {query.error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">The governed snapshot could not be generated. Confirm that the Sprint C migration is applied and try again.</p>}
    {!governanceReady && <article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black text-amber-950">Governance snapshots are not configured yet</h2><p className="mt-2 text-sm leading-6 text-amber-800">Live quality checks remain available. Apply the Sprint C governance migration to enable KPI definitions, historical trends and scheduled snapshots.</p></article>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><ScoreCard title="Overall quality" value={quality.score} /><LcdboCommandMetricCard icon={Database} label="Completeness" value={`${quality.completeness}%`} /><LcdboCommandMetricCard icon={ShieldCheck} label="Consistency" value={`${quality.consistency}%`} /><LcdboCommandMetricCard icon={CheckCircle2} label="Coverage" value={`${quality.coverage}%`} /></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{quality.issues.map((issue) => <article key={issue.code} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.12em] text-slate-500">{issue.code.replaceAll("_", " ")}</p><h2 className="mt-2 font-black text-[#0B2E59]">{issue.label}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-black ${issue.count ? issue.severity === "high" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-900" : "bg-emerald-100 text-emerald-800"}`}>{issue.count}</span></div><p className="mt-3 text-sm leading-6 text-slate-500">{issue.detail}</p></article>)}</section>
    <section className="grid gap-5 lg:grid-cols-2">{trendData.length ? <IntelligenceBarChart title="Quality score trend" data={trendData} /> : <article className="rounded-2xl border border-dashed border-slate-300 bg-white p-5"><h2 className="font-black text-[#0B2E59]">No quality snapshots yet</h2><p className="mt-2 text-sm leading-6 text-slate-500">Generate the first governed snapshot to establish a quality-score baseline and unlock period-over-period trends.</p></article>}<article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-600" /><h2 className="text-xl font-black text-[#0B2E59]">Programme monitoring alerts</h2></div><div className="mt-4 space-y-3">{health.alerts.map((alert) => <div key={alert.code} className="flex items-start justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-bold text-slate-800">{alert.label}</p><p className="mt-1 text-xs text-slate-500">{alert.detail}</p></div><span className="font-black text-[#0B2E59]">{alert.count}</span></div>)}</div></article></section>
  </div></main>;
}

function ScoreCard({ title, value }: { title: string; value: number }) { const color = value >= 85 ? "text-emerald-700" : value >= 65 ? "text-amber-700" : "text-rose-700"; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className={`text-5xl font-black ${color}`}>{value}</p><p className="mt-1 text-xs font-black uppercase tracking-[0.12em] text-slate-500">{title} / 100</p><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#008751]" style={{ width: `${value}%` }} /></div></article>; }
