export type UserRole =
  | "public"
  | "msme"
  | "association_officer"
  | "reviewer"
  | "boi_executive"
  | "programme_officer"
  | "assessment_officer"
  | "field_officer"
  | "auditor"
  | "fccpc_officer"
  | "nrs_officer"
  | "firs_officer"
  | "admin"
  | "super_admin";
