import { getPublicCredentialVerificationByToken } from "@/lib/data/public-verification";
import { credentialVerifyUrl } from "@/lib/data/credential-trust";
import { createServiceRoleSupabaseClient } from "@/lib/supabase/server";
import { checkRateLimit } from "@/lib/http/rate-limit";

const formatDate = (value?: string | null) => {
  if (!value) return "Not Available";

  return new Date(value).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
};

export async function GET(_request: Request, { params }: { params: Promise<{ token: string }> }) {
  const rate = await checkRateLimit({ scope: "verify-summary", limit: 30, windowMs: 60_000 });
  if (!rate.ok) return new Response("Rate limited", { status: 429 });

  const { token } = await params;
  const result = await getPublicCredentialVerificationByToken(decodeURIComponent(token));

  if (!result.ok) {
    return new Response("Verification not found", { status: 404 });
  }

  const detail = result.detail;
  const supabase = await createServiceRoleSupabaseClient();
  const { data: validation } = await supabase
    .from("validation_results")
    .select("validated_at")
    .eq("msme_id", detail.msme.id)
    .maybeSingle();

  const issuedDate = formatDate(detail.digitalId?.issued_at ?? detail.msme.issued_at);
  const lastValidated = formatDate(validation?.validated_at ?? detail.digitalId?.issued_at ?? detail.msme.issued_at);
  const verificationUrl = credentialVerifyUrl(token);

  const rows: Array<[string, string]> = [
    ["Business Name", detail.msme.business_name],
    ["DBIN ID", detail.resolvedId],
    ["Credential Status", "Active"],
    ["Jurisdiction", detail.msme.state ?? "Not Available"],
    ["Category", detail.msme.sector ?? "Not Available"],
    ["Issued Date", issuedDate],
    ["Last Validated Date", lastValidated],
  ];

  const lines = [
    "Verification Summary",
    "Digital Business Identity Network (DBIN)",
    "",
    ...rows.map(([label, value]) => `${label}: ${value || "Not Available"}`),
    "",
    "Generated by Digital Business Identity Network (DBIN)",
    `Verification URL: ${verificationUrl}`,
  ];

  const escapePdf = (value: string) => value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
  const contentStream = [
    "BT",
    "/F1 20 Tf",
    "50 790 Td",
    `(${escapePdf(lines[0] ?? "")}) Tj`,
    "0 -28 Td",
    "/F1 12 Tf",
    `(${escapePdf(lines[1] ?? "")}) Tj`,
    "0 -28 Td",
    "/F1 11 Tf",
    ...lines.slice(2).flatMap((line) => [`(${escapePdf(line)}) Tj`, "0 -18 Td"]),
    "ET",
  ].join("\n");

  const streamLength = new TextEncoder().encode(contentStream).length;
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${streamLength} >> stream\n${contentStream}\nendstream endobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const object of objects) {
    offsets.push(new TextEncoder().encode(pdf).length);
    pdf += `${object}\n`;
  }

  const xrefStart = new TextEncoder().encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets.slice(1)) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new Response(new TextEncoder().encode(pdf), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="verification-summary-${detail.resolvedId}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
