-- DBIN DLPI Phase 2.5: registry foundation stabilization.
-- Harden application references, NPIN governance, lifecycle audit metadata,
-- and performance indexes without adding Phase 3 registry workflows.

create table if not exists public.property_application_sequences (
  sequence_year integer primary key,
  last_value bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint property_application_sequences_year_check check (sequence_year >= 2026),
  constraint property_application_sequences_value_check check (last_value >= 0)
);

alter table public.properties
  add column if not exists application_reference text,
  add column if not exists application_submitted_at timestamptz;

alter table public.property_documents
  add column if not exists superseded_by uuid references public.property_documents(id) on delete set null,
  add column if not exists superseded_at timestamptz,
  add column if not exists superseded_by_user_id uuid references public.users(id) on delete set null;

create unique index if not exists idx_properties_application_reference
  on public.properties(application_reference)
  where application_reference is not null;

create index if not exists idx_properties_registered_by_updated
  on public.properties(registered_by, updated_at desc)
  where registered_by is not null;

create index if not exists idx_properties_application_submitted
  on public.properties(application_submitted_at desc)
  where application_submitted_at is not null;

create index if not exists idx_property_addresses_property
  on public.property_addresses(property_id);

create index if not exists idx_property_documents_superseded_by
  on public.property_documents(superseded_by)
  where superseded_by is not null;

create index if not exists idx_property_documents_property_type_status
  on public.property_documents(property_id, document_type, status)
  where property_id is not null;

alter table public.property_status_history drop constraint if exists property_status_history_new_status_check;
alter table public.property_status_history
  add constraint property_status_history_new_status_check check (new_status in (
    'draft',
    'submitted',
    'under_review',
    'verified',
    'active',
    'transferred',
    'suspended',
    'disputed',
    'archived',
    'cancelled',
    'rejected'
  ));

drop trigger if exists set_property_application_sequences_updated_at on public.property_application_sequences;
create trigger set_property_application_sequences_updated_at before update on public.property_application_sequences
  for each row execute function public.set_platform_foundation_updated_at();

alter table public.property_application_sequences enable row level security;

create or replace function public.generate_property_application_reference(target_year integer default extract(year from now())::integer)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  app_year integer;
  next_value bigint;
begin
  app_year := coalesce(target_year, extract(year from now())::integer);

  if app_year < 2026 then
    raise exception 'Application reference year is invalid.';
  end if;

  if current_user not in ('postgres', 'supabase_admin')
     and current_setting('request.jwt.claim.role', true) is distinct from 'service_role' then
    raise exception 'Application references can only be generated by trusted registry services.';
  end if;

  insert into public.property_application_sequences (sequence_year, last_value)
  values (app_year, 0)
  on conflict (sequence_year) do nothing;

  update public.property_application_sequences
  set last_value = last_value + 1,
      updated_at = now()
  where sequence_year = app_year
  returning last_value into next_value;

  return 'DLPI-APP-' || app_year::text || '-' || lpad(next_value::text, 6, '0');
end;
$$;

create or replace function public.generate_property_npin(target_state_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  state_code text;
  npin_state_code text;
  next_value bigint;
begin
  if current_user not in ('postgres', 'supabase_admin')
     and current_setting('request.jwt.claim.role', true) is distinct from 'service_role'
     and not public.property_can_manage_registry(target_state_id, null, null) then
    raise exception 'NPIN generation is restricted to trusted registry approval services.';
  end if;

  select code into state_code
  from public.states
  where id = target_state_id;

  if state_code is null then
    raise exception 'A valid state is required to generate an NPIN.';
  end if;

  npin_state_code := case when upper(state_code) = 'FC' then 'FCT' else upper(state_code) end;

  insert into public.property_npin_sequences (state_id, state_code, last_value)
  values (target_state_id, npin_state_code, 0)
  on conflict (state_id) do nothing;

  update public.property_npin_sequences
  set last_value = last_value + 1,
      state_code = npin_state_code,
      updated_at = now()
  where state_id = target_state_id
  returning last_value into next_value;

  return 'NPIN-' || npin_state_code || '-' || lpad(next_value::text, 9, '0');
end;
$$;

revoke all on function public.generate_property_application_reference(integer) from public;
grant execute on function public.generate_property_application_reference(integer) to service_role;

revoke all on function public.generate_property_npin(uuid) from public;
grant execute on function public.generate_property_npin(uuid) to service_role;

do $$
declare
  property_row record;
  generated_reference text;
begin
  for property_row in
    select id, created_at
    from public.properties
    where application_reference is null
      and status <> 'draft'
    order by created_at, id
  loop
    generated_reference := public.generate_property_application_reference(extract(year from coalesce(property_row.created_at, now()))::integer);

    update public.properties
    set
      application_reference = generated_reference,
      application_submitted_at = coalesce(application_submitted_at, created_at),
      metadata = metadata || jsonb_build_object('application_reference_backfilled', true),
      updated_at = now()
    where id = property_row.id;
  end loop;
end;
$$;
